### ISSUE TITLE
Function `texture_gpu_white` is declared but not implemented

### ISSUE THREAD

**Issue by vogr** [drohmer/inf443_vcl#1]
Hello,

It appears that the function `vcl::texture_gpu_white()` is declared in the header file [`vcl/opengl/texture/texture_gpu/texture_gpu.hpp`](https://github.com/drohmer/inf443_vcl/blob/411093caf14995805981db9164fd29953a7454cb/vcl/opengl/texture/texture_gpu/texture_gpu.hpp):
https://github.com/drohmer/inf443_vcl/blob/411093caf14995805981db9164fd29953a7454cb/vcl/opengl/texture/texture_gpu/texture_gpu.hpp#L21

but the correspong source file [`texture_gpu.cpp`](411093caf14995805981db9164fd29953a7454cb) does not contain a definition for this function. This is problematic, because my IDE offers this function through code completion even though its use will result in an error at link time. Searching for the function name in this repository indicates that this function is not referenced anywhere.

Simply removing this declaration would leave the library in a functional state. However, I think that such a function would be quite useful, as it would give user code the possibility to create meshes with a sensible default texture.

I would gladly make a PR, but I don't know how this function would find the actual id of the white texture.

~ Valentin

**Comment by drohmer** [comment]
Yes true, this is a rest of some aborted attempt that I didn't clean correctly. This function signature can be safely removed. A default white texture is always available from the variable scene.texture_white in setup_data and frame_draw.

The corresponding code to generate the white texture is the following:
```c++
const image_raw white{1,1,image_color_type::rgba,{255,255,255,255}};
scene.texture_white = create_texture_gpu(white);
```

It can be found in the file main/helper_scene/helper_scene.cpp (function setup_scene)

**Comment by vogr** [comment]
Thank you for the reply ! I will therefore close this issue.
